// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { Requirement } from "./Requirement";
import type { Trigger } from "./Trigger";

export type Ability = { trigger: Trigger, requirements: Array<Requirement>, effects: Array<Effect>, };
