// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardEntity } from "./CardEntity";
import type { Hero } from "./Hero";
import type { MinionEntity } from "./MinionEntity";

export type Board = { deck: Array<CardEntity>, hand: Array<CardEntity>, graveyard: Array<MinionEntity>, battlefield: Array<MinionEntity>, hero: Hero, base_mana: number, mana: number, };
