// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowUpAbility } from "./FollowUpAbility";
import type { TargetSpec } from "./TargetSpec";

export type Effect = { "Buff": { target_spec: TargetSpec, attack: number, defence: number, } } | { "Damage": { target_spec: TargetSpec, damage: number, } } | { "Draw": { draw_amount: number, follow_up: FollowUpAbility | null, } } | { "ReturnToHand": { target_spec: TargetSpec, cost_reduction: number | null, } } | { "Destroy": { target_spec: TargetSpec, } } | { "Summon": { minion_card_id: number, summon_amount: number, } };
