// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntityBase = { entity_id: string, cost: number, turns_in_hand: number, just_drawn: boolean, };
