// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaledAmount } from "./ScaledAmount";

export type FollowUpEffect = { "Discount": { scaled_amount: ScaledAmount, } } | { "Copy": { copy_amount: number, } };
