// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowUpEffect } from "./FollowUpEffect";
import type { FollowUpRequirement } from "./FollowUpRequirement";

export type FollowUpAbility = { follow_up_requirements: Array<FollowUpRequirement>, follow_up_effects: Array<FollowUpEffect>, };
