// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { Color } from "./Color";
import type { IncantationAttribute } from "./IncantationAttribute";

export type IncantationCard = { id: number, name: string, description: string | null, flavor_text: string | null, color: Color, base_cost: number, image_url: string, abilities: Array<Ability>, attributes: Array<IncantationAttribute>, is_token: boolean, };
