// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityBase } from "./EntityBase";
import type { MinionCard } from "./MinionCard";

export type MinionEntity = { card: MinionCard, base: EntityBase, attack: number, defence: number, exhausted: boolean, };
