// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { Color } from "./Color";
import type { MinionAttribute } from "./MinionAttribute";
import type { Race } from "./Race";

export type MinionCard = { id: number, name: string, description: string | null, flavor_text: string | null, color: Color, base_cost: number, image_url: string, abilities: Array<Ability>, base_attack: number, base_defence: number, races: Array<Race>, attributes: Array<MinionAttribute>, };
