// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaledBy } from "./ScaledBy";

export type ScaledAmount = { scalar: number, scaled_by: ScaledBy | null, };
