// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityBase } from "./EntityBase";
import type { IncantationCard } from "./IncantationCard";

export type IncantationEntity = { card: IncantationCard, base: EntityBase, };
